"""Shared game and networking configuration."""

SERVER_PORT = 9090
SERVER_TICK_HZ = 60
CLIENT_SEND_HZ = 60
SERVER_REQUIRED_PLAYERS = 2
SERVER_MENU_POLL_HZ = 10

CLIENT_PLAYER_ID = 1
CLIENT_SERVER_IP = "192.168.137.23"
CLIENT_AUTO_START_GAME = True
CLIENT_MENU_POLL_HZ = 10
CLIENT_SPAWN_X = 64.0
CLIENT_SPAWN_Y = 64.0
CLIENT_SPAWN_HEADING = 0.0
